// Master defaults for Service Desk Officers and Hospital Departments
// Serves as immediate hydration on client load, preventing any UI blank state.

export const DEFAULT_OFFICERS = [
  { name: 'MUHAMMAD.NAVEED', email: 'muhammad.naveed@tabbaheart.org' },
  { name: 'MUHAMMAD.JUNAID', email: 'muhammad.junaid@tabbaheart.org' },
  { name: 'MURSALEEN.AMANULLAH', email: 'mursaleen.amanullah@tabbaheart.org' },
  { name: 'MUHAMMAD.OWAIS', email: 'muhammad.owais@tabbaheart.org' },
  { name: 'HASSAN.HAIDER', email: 'hassan.haider@tabbaheart.org' },
  { name: 'ANIS.ALI', email: 'anis.ali@tabbaheart.org' }
];

export const DEFAULT_DEPARTMENTS = [
  "ATF - Accounts",
  "Accommodation Services",
  "Admin Secretariat",
  "Administration",
  "Allied Health Sciences",
  "Ambulatory Services",
  "Anesthesia",
  "Bio-Medical",
  "C.S.S.D.",
  "CCU",
  "CME committee",
  "CT Surgery & Anesthesia",
  "Cardiac Anesthesia",
  "Cardiac Cath Lab",
  "Cardiac Emergency",
  "Cardiac Perfusion",
  "Cardiology",
  "Cardiology (ER)",
  "Cardiothoracic Surgery",
  "Cath Lab",
  "Clinical Administration",
  "Clinical Laboratory",
  "Clinical Research",
  "Clinical Research CTS",
  "Clinical Research Cardiology",
  "Clinical Research Project",
  "Clinical Secretariat",
  "Collection Unit - (GI)",
  "Collection Unit - (GJ)",
  "Communication",
  "Community Pharmacy",
  "Contact Centre",
  "DHA (Clinic)",
  "DeparmentT01",
  "Diabetic & Endocr. Serv.",
  "Diagnostic Services",
  "Diagnostics Services",
  "EP & Arrhythmia Services",
  "Echo Lab",
  "Echocardioghraphy",
  "Elite/Special Squad",
  "Emergency Room",
  "Facility Mgt. & Eng. Services",
  "Filter & Consultant Clinic",
  "Finance and Accounts",
  "General Ward",
  "H.I.M.S.",
  "HDU",
  "Human Resource",
  "I.C.T",
  "Infection Control",
  "Inpatient Administration & Other Services",
  "Inpatient Consultation Services",
  "Intensive Care Unit",
  "Intensive Care Unit - II",
  "Internal Audit",
  "Lab Collection Unit",
  "Laboratory",
  "Laboratory (Obsolete)",
  "Laundry",
  "Library",
  "LuckyOne Diagnostic Services",
  "M.I.S.",
  "Marketing & Outreach Serv.",
  "Med. Prof. Services",
  "Medical & Clinical",
  "Medical & Clinical Affairs",
  "Medical Prof. Services",
  "Medical Records",
  "Medical Services",
  "Non Invasive Cardiology",
  "Nuclear",
  "Nuclear Cardiology",
  "Nursing (CCU)",
  "Nursing Education Services",
  "Nursing Secretariat",
  "Nursing Services",
  "Operation Room",
  "Other General Procedures",
  "Outreach Marketing",
  "Outreach Medical Centre (GJ)",
  "Outreach Services / OP-DHA-Clinics",
  "Oxygen, Vent & Other Services",
  "P.B.S.D.",
  "Patient Relation",
  "Patient Safety & QAD",
  "Patient Welfare Department",
  "Pharmacy Services",
  "Physiology",
  "Prev. Card & Rehab",
  "Private - I",
  "Private - II",
  "Quality Assurance THI",
  "Radiology",
  "Safety and Security",
  "School of Nursing",
  "Step Down Unit",
  "Supply Chain Management",
  "Support Services",
  "Surgery",
  "THI Medical Centre - DHA",
  "THI Medical Centre - Doctor Lane HYD.",
  "THI Medical Centre - HYD.",
  "THI Medical Centre - KE",
  "THI Medical Centre - Malir Cantt.",
  "THI Medical Centre - North Karachi",
  "THI Medical Centre - North Nazimabad",
  "THI Medical Centre - Quetta",
  "TKI Diagnostic Services",
  "Transport Services",
  "Warehouse",
  "Welfare / Coordination"
];
